# Generated by Django 4.2.7 on 2023-12-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_cardtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cardtext',
        ),
    ]
